/**************************************************************************
 *
 * Copyright 2015 VMware, Inc.
 * All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 **************************************************************************/


#include <stdio.h>

#include <iostream>
#include <sstream>
#include <memory>

#include "state_writer.hpp"
#include "d3dimports.hpp"
#include "d3dstate.hpp"


namespace d3dstate {

static void
dumpViewport(StateWriter &writer, IDirect3DDevice2 *pDevice)
{
    writer.beginMember("Viewport");
    writer.beginObject();

    IDirect3DViewport2 *vp2 = nullptr;
    HRESULT hr = pDevice->GetCurrentViewport(&vp2);
    if (SUCCEEDED(hr) && vp2) {
        D3DVIEWPORT vp;
        ZeroMemory(&vp, sizeof(vp));
        vp.dwSize = sizeof(vp);
        hr = vp2->GetViewport(&vp);
        if (SUCCEEDED(hr)) {
            writer.writeIntMember("X", vp.dwX);
            writer.writeIntMember("Y", vp.dwY);
            writer.writeIntMember("Width", vp.dwWidth);
            writer.writeIntMember("Height", vp.dwHeight);
            writer.writeFloatMember("MinZ", vp.dvMinZ);
            writer.writeFloatMember("MaxZ", vp.dvMaxZ);
        }
    }

    writer.endObject();
    writer.endMember();
}

static void
dumpRenderstate(StateWriter &writer, IDirect3DDevice2 *pDevice)
{
#define _DUMP_RS_INT(x) { \
    DWORD rsDword = 0; \
    pDevice->GetRenderState(x, &rsDword); \
    writer.writeIntMember(#x, rsDword); \
}

#define _DUMP_RS_FLOAT(x) { \
    float rsFloat = 0.0f; \
    pDevice->GetRenderState(x, (DWORD *)&rsFloat); \
    writer.writeFloatMember(#x, rsFloat); \
}

    /* TODO */
    writer.beginMember("parameters");
    writer.beginObject();

    _DUMP_RS_INT(D3DRENDERSTATE_ANTIALIAS);
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREPERSPECTIVE);
    _DUMP_RS_INT(D3DRENDERSTATE_ZENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_FILLMODE);
    _DUMP_RS_INT(D3DRENDERSTATE_SHADEMODE);
    _DUMP_RS_INT(D3DRENDERSTATE_LINEPATTERN);
    _DUMP_RS_INT(D3DRENDERSTATE_ZWRITEENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_ALPHATESTENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_LASTPIXEL);
    _DUMP_RS_INT(D3DRENDERSTATE_SRCBLEND);
    _DUMP_RS_INT(D3DRENDERSTATE_DESTBLEND);
    _DUMP_RS_INT(D3DRENDERSTATE_CULLMODE);
    _DUMP_RS_INT(D3DRENDERSTATE_ZFUNC);
    _DUMP_RS_INT(D3DRENDERSTATE_ALPHAREF);
    _DUMP_RS_INT(D3DRENDERSTATE_ALPHAFUNC);
    _DUMP_RS_INT(D3DRENDERSTATE_DITHERENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_ALPHABLENDENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_FOGENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_SPECULARENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_ZVISIBLE);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEDALPHA);
    _DUMP_RS_INT(D3DRENDERSTATE_FOGCOLOR);
    _DUMP_RS_INT(D3DRENDERSTATE_FOGTABLEMODE);
    _DUMP_RS_FLOAT(D3DRENDERSTATE_FOGSTART);
    _DUMP_RS_FLOAT(D3DRENDERSTATE_FOGEND);
    _DUMP_RS_FLOAT(D3DRENDERSTATE_FOGDENSITY);
    _DUMP_RS_INT(D3DRENDERSTATE_EDGEANTIALIAS);
    _DUMP_RS_INT(D3DRENDERSTATE_COLORKEYENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_ZBIAS);
    _DUMP_RS_INT(D3DRENDERSTATE_RANGEFOGENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_STENCILENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_STENCILFAIL);
    _DUMP_RS_INT(D3DRENDERSTATE_STENCILZFAIL);
    _DUMP_RS_INT(D3DRENDERSTATE_STENCILPASS);
    _DUMP_RS_INT(D3DRENDERSTATE_STENCILFUNC);
    _DUMP_RS_INT(D3DRENDERSTATE_STENCILREF);
    _DUMP_RS_INT(D3DRENDERSTATE_STENCILMASK);
    _DUMP_RS_INT(D3DRENDERSTATE_STENCILWRITEMASK);
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREFACTOR);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAP0);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAP1);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAP2);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAP3);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAP4);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAP5);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAP6);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAP7);
    _DUMP_RS_INT(D3DRENDERSTATE_CLIPPING);
    _DUMP_RS_INT(D3DRENDERSTATE_LIGHTING);
    _DUMP_RS_INT(D3DRENDERSTATE_EXTENTS);
    _DUMP_RS_INT(D3DRENDERSTATE_AMBIENT);
    _DUMP_RS_INT(D3DRENDERSTATE_FOGVERTEXMODE);
    _DUMP_RS_INT(D3DRENDERSTATE_COLORVERTEX);
    _DUMP_RS_INT(D3DRENDERSTATE_LOCALVIEWER);
    _DUMP_RS_INT(D3DRENDERSTATE_NORMALIZENORMALS);
    _DUMP_RS_INT(D3DRENDERSTATE_COLORKEYBLENDENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_DIFFUSEMATERIALSOURCE);
    _DUMP_RS_INT(D3DRENDERSTATE_SPECULARMATERIALSOURCE);
    _DUMP_RS_INT(D3DRENDERSTATE_AMBIENTMATERIALSOURCE);
    _DUMP_RS_INT(D3DRENDERSTATE_EMISSIVEMATERIALSOURCE);
    _DUMP_RS_INT(D3DRENDERSTATE_VERTEXBLEND);
    _DUMP_RS_INT(D3DRENDERSTATE_CLIPPLANEENABLE);

    // D3D6 and lower
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREHANDLE);
    _DUMP_RS_INT(D3DRENDERSTATE_ANTIALIAS);
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREADDRESS);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAPU);
    _DUMP_RS_INT(D3DRENDERSTATE_WRAPV);
    _DUMP_RS_INT(D3DRENDERSTATE_MONOENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_ROP2);
    _DUMP_RS_INT(D3DRENDERSTATE_PLANEMASK);
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREMAG);
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREMIN);
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREMAPBLEND);
    _DUMP_RS_INT(D3DRENDERSTATE_SUBPIXEL);
    _DUMP_RS_INT(D3DRENDERSTATE_SUBPIXELX);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_OLDALPHABLENDENABLE);
    _DUMP_RS_INT(D3DRENDERSTATE_BORDERCOLOR);
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREADDRESSU);
    _DUMP_RS_INT(D3DRENDERSTATE_TEXTUREADDRESSV);
    _DUMP_RS_INT(D3DRENDERSTATE_MIPMAPLODBIAS);
    _DUMP_RS_INT(D3DRENDERSTATE_ANISOTROPY);
    _DUMP_RS_INT(D3DRENDERSTATE_FLUSHBATCH);
    _DUMP_RS_INT(D3DRENDERSTATE_TRANSLUCENTSORTINDEPENDENT);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN00);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN01);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN02);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN03);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN04);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN05);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN06);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN07);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN08);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN09);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN10);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN11);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN12);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN13);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN14);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN15);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN16);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN17);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN18);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN19);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN20);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN21);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN22);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN23);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN24);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN25);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN26);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN27);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN28);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN29);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN30);
    _DUMP_RS_INT(D3DRENDERSTATE_STIPPLEPATTERN31);

#undef _DUMP_RS_INT
#undef _DUMP_RS_FLOAT

    dumpViewport(writer, pDevice);

    /*
     * TODO: texture stage states couldn't be retrieved in d3d5 and prior.
     * If we want to dump their states we have save states during sets.
     * And also parse execute buffer command stream if application using them
     * to retrieve states or textures.
     */

    writer.endObject();
    writer.endMember(); // parameters
}

void
dumpDevice(StateWriter &writer, IDirect3DDevice2 *pDevice)
{
    dumpRenderstate(writer, pDevice);

    writer.beginMember("shaders");
    writer.beginObject();
    writer.endObject();
    writer.endMember(); // shaders

    dumpTextures(writer, pDevice);

    dumpFramebuffer(writer, pDevice);
}


} /* namespace d3dstate */
