name: build

on:
  push:
  pull_request:

jobs:
  msvc:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86]
        target: [win32, win64]
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1
        submodules: recursive
    - name: Cache Downloads
      id: cache-downloads
      uses: actions/cache@v5
      with:
        path: |
          *qtbase-*.7z
          *qttools-*.7z
        key: ${{ runner.os }}-${{ matrix.target }}-${{ matrix.arch }}-5.15.2-1
    - name: Build
      run: .\ci\build-msvc.ps1 -arch ${{ matrix.arch }} -target ${{ matrix.target }} -config Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: apitrace-${{ matrix.target }}-${{ matrix.arch }}
        path: build/apitrace-*.7z
        if-no-files-found: error

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: [msvc]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1
        submodules: recursive
    - uses: actions/download-artifact@v8
      id: download
      with:
        path: artifacts
    - run: ls -lR ${{ steps.download.outputs.download-path }}
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >
        gh release create --draft --title "${{ github.ref_name }}" --generate-notes "${{ github.ref_name }}"
        ${{ steps.download.outputs.download-path }}/*/apitrace-*.tar.bz2
        ${{ steps.download.outputs.download-path }}/*/apitrace-*.7z
